<body>
    <div>
        <h2 style='font-family: cursive; font-size: 40px;'>Factorizacion LU</h2>
<!--         <img src= alt=middle style="height: 340px"> -->
    </div>
</body>

<h3 style="font-family: 'Courier New'; font-size:25px"
    >Formulación matemática</h3>

$Ax=b$
<br>
$LUx=b$
<br>
$Ly=b$
<br>

<h3 style="font-family: 'Courier New'; font-size:25px"
    >Valores iniciales</h3>

A: Matriz cuadrado de largo mxm.
<br>
b: Vector de tamaño m.

<h3 style="font-family: 'Courier New'; font-size:25px"
    >Ventajas y desventajas</h3>

<table style="width:100%; text-align: left; font-size: 14px">
    <tr style="text-align: left;">
        <th style="text-align: left;">Ventajas</th>
        <th style="text-align: left;">Desventajas</th>
    </tr>
    <tr>
        <td style="text-align: left;">Es un metodo computacionalmente eficiente.</td>       
        <td style="text-align: left;">La matriz A debe ser cuadrada.</td>
    </tr>
</table>

<h3 style="font-family: 'Courier New'; font-size:25px"
    >Pseudocódigo</h3>

<ol>
    <li>Calcular las matrices L y U apartir de A</li>
    <li>Y = sustitucionHaciaDelante de L y b</li>
    <li>x = sustitucionHaciaAtras de L y Y</li>
    <li>Retornar x</li>
</ol>

<h3 style="font-family: 'Courier New'; font-size:25px">Octave</h3>

In [8]:
function [a, l] = getLowUpperMatrix(a, m, n)
%   Funcion para obtener una matriz triangular superior e inferior
%   :param a: una matriz
%   :param m: tamaño de las filas de la matriz
%   :param n: tamaño de las columnas de la matriz
%   :return: matriz triangular superior e inferior
    l = zeros(m);
    for i=1:m
        if a(i,i) == 0
            disp('Error: Zero division exception.');
        end
        for j=i:m
            if i!=j
                #Coeficiente que sirve para sacar gauss-jordan
                coef = a(j, i)/a(i, i);
                #Guarda el coeficiente en la matriz inferior
                l(j,i) = coef;
                for k=i:(m)
                    #Saca gauss-jordan
                    a(j, k) = a(j, k) - coef * a(i, k);
                end
            else
                l(j,i) = 1;
            end
        end
    end
end

function [x] = backwardSubstitution(a, m, n)
%   Funcion para obtener la sustitucion hacia atras de una matriz superior
%   :param a: una matriz superior
%   :param m: tamaño de las filas de la matriz
%   :param n: tamaño de las columnas de la matriz
%   :return: matriz con el valor de cada x
    %Calcula el valor de x_m
    x_i(m) = [a(m,n)/a(m,m)];
    for i=m:-1:1
        x_sum = 0;
        %Suma la multiplicacion de la contante junto con la variable encontrada
        for j=i+1:m
            x_sum = x_sum + a(i, j) * x_i(j);
        end
        %Obtiene el valor de x_i
        x_i(i) = (a(i, n)-x_sum)/a(i,i);
    end
    x = x_i';
end

function [y] = forwardSubstitution(a, m, n)
%   Funcion para obtener la sustitucion hacia delante de una matriz inferior
%   :param a: una matriz inferior
%   :param m: tamaño de las filas de la matriz
%   :param n: tamaño de las columnas de la matriz
%   :return: matriz con el valor de cada y
    x_i(m) = 0;
    %Calcula el valor de x_1
    x_i(1) = [a(1,n)];
    for i=2:m
        x_sum = 0;
        %Suma la multiplicacion de la contante junto con la variable encontrada
        for j=1:i
            x_sum = x_sum + a(i, j) * x_i(j);
        end
        %Obtiene el valor de x_i
        x_i(i) = (a(i, n)-x_sum);
    end
    y = x_i';
end

function [x] = calcLU(a, b)
%   Metodo de Factorizacion LU para resolver un sistema A x = B
%   :param a: una matriz
%   :param b: un vector
%   :return: matriz con el valor de cada x
    [m n] = size(a);
    %Obtiene la matriz superior e inferior
    [u l] = getLowUpperMatrix(a, m, n);
    u
    l
    %Concatena la matriz inferior con b
    l = [l b];
    %Obtiene la matriz de soluciones de y
    [y] = forwardSubstitution(l, m, n + 1);
    y
    %Concatena la matriz superior con y
    u = [u y];
    %Obtiene la matriz de soluciones
    [x] = backwardSubstitution(u, m, n + 1);
end

<h3 style="font-family: 'Courier New'; font-size:25px">Python</h3>

In [37]:
from sympy import Matrix

def getLowUpperTriangular(a, m, n):
    """
    Funcion para obtener una matriz triangular superior e inferior
    :param a: una matriz
    :param m: tamaño de las filas de la matriz
    :param n: tamaño de las columnas de la matriz
    :return: matriz triangular superior e inferior
    """
    l = []
    for i in range(m):
        l.append([0] * m)
    for i in range(m):
        if a[i][i] == 0:
            print('Error: Zero division exception.')
        for j in range(i,m):
            if i != j:
                #Coeficiente que sirve para sacar gauss-jordan
                coef = a[j][i] / a[i][i]
                #Guarda el coeficiente en la matriz inferior
                l[j][i] = coef
                for k in range(i, n):
                    #Saca gauss-jordan
                    a[j][k] -= coef * a[i][k]
            else:
                l[j][i] = 1
    return a, l


def backwardSubstitution(a, m, n):
    """
    Funcion para obtener la sustitucion hacia atras de una matriz superior
    :param a: una matriz superior
    :param m: tamaño de las filas de la matriz
    :param n: tamaño de las columnas de la matriz
    :return: matriz con el valor de cada x
    """
    x_i = [0] * m
    #Calcula el valor de x_m
    x_i[m-1] = a[m-1][n-1]/a[m-1][m-1]
    for i in range(m-1, -1, -1):
        x_sum = 0
        #Suma la multiplicacion de la contante junto con la variable encontrada
        for j in range(i+1, m):
            x_sum += a[i][j] * x_i[j]
        #Obtiene el valor de x_i
        x_i[i] = (a[i][m] - x_sum)/a[i][i]
    return x_i
    

def forwardSubstitution(a, m, n):
    """
    Funcion para obtener la sustitucion hacia delante de una matriz inferior
    :param a: una matriz inferior
    :param m: tamaño de las filas de la matriz
    :param n: tamaño de las columnas de la matriz
    :return: matriz con el valor de cada y
    """
    x_i = [0] * m
    #Calcula el valor de x_0
    x_i[0] = a[0][n-1]
    for i in range(1, m):
        x_sum = 0
        #Suma la multiplicacion de la contante junto con la variable encontrada
        for j in range(0, i):
            x_sum += a[i][j] * x_i[j]
        #Obtiene el valor de x_i
        x_i[i] = (a[i][m] - x_sum)
    return x_i


def appendColumn(a, b):
    """
    Adjunta una columna B a una matriz A
    :param a: una matriz
    :return: matriz con la columna B adjunta
    """
    m = len(a)
    for i in range(m):
        a[i].append(b[i])
    return a


def calcLU(a, b):
    """
     Metodo de Factorizacion LU para resolver un sistema A x = B
    :param a: una matriz
    :param b: un vector 
    :return: matriz con el valor de cada x
    """
    #Obtiene el tamaño de la matriz
    m = len(a) 
    n = len(a[0])
    #Obtiene la matriz triangular superior e inferior
    u, l = getLowUpperTriangular(a, m, n)
    
    #Obtiene la matriz de soluciones
    y = forwardSubstitution(appendColumn(l, b), m, n + 1)
    x = backwardSubstitution(appendColumn(u, y), m, n + 1)
    return Matrix(x)

<h3 style="font-family: 'Courier New'; font-size:25px">Ejemplo Numérico</h3>

<h5 style="font-family: 'Courier New'; font-size:16px">Python</h5>

In [38]:
a = [[2, 3, 4], [4, 5, 10], [4, 8, 2]]
b = [6, 16, 2]
print(calcLU(a, b))

Matrix([[4.00000000000000], [-2.00000000000000], [1.00000000000000]])


<h5 style="font-family: 'Courier New'; font-size:16px">Octave</h5>

In [9]:
a = [4 -2 1; 20 -7 12; -8 13 17];
b = [11; 70; 17];

[x] = calcLU(a, b)

a = [2 3 4; 4 5 10; 4 8 2];
b = [6; 16; 2];

[x] = calcLU(a, b)

disp('Quiz')
a = [2 -6 -1; -3 -1 7; -8 1 -2];
b = [-38; -34; -20];

[x] = calcLU(a, b)


u =

   4  -2   1
   0   3   7
   0   0  -2

l =

   1   0   0
   5   1   0
  -2   3   1

y =

   11
   15
   -6

x =

   1
  -2
   3

u =

   2   3   4
   0  -1   2
   0   0  -2

l =

   1   0   0
   2   1   0
   2  -2   1

y =

   6
   4
  -2

x =

   4
  -2
   1

Quiz
u =

    2.00000   -6.00000   -1.00000
    0.00000  -10.00000    5.50000
    0.00000    0.00000  -18.65000

l =

   1.00000   0.00000   0.00000
  -1.50000   1.00000   0.00000
  -4.00000   2.30000   1.00000

y =

  -38.000
  -91.000
   37.300

x =

   4.0000
   8.0000
  -2.0000

